# based on this websockets example: https://fly.io/blog/websockets-and-fly/

app = 'YOUR_APP_NAME'
primary_region = 'iad'

[build]
  dockerfile = 'Containerfile'

[[vm]]
  size = 'shared-cpu-1x'

[[services]]
  internal_port = 8910
  protocol = 'tcp'
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1

  [[services.ports]]
    handlers = ["tls", "http"]
    port = "443"

  [services.concurrency]
    hard_limit = 250
    soft_limit = 200

  [[services.tcp_checks]]
    interval = 10000
    timeout = 2000
